import pygame as pg
from typing import Protocol

class UIComponent(Protocol):
    def update(self, dt: float) -> None: ...
    def draw(self, screen: pg.Surface) -> None: ...
    def move_by(self, dx: int, dy: int) -> None: ...
    def set_pos(self, x: int, y: int) -> None: ...
